### PR TITLE
docs: add samples from video/cloud-client/labels

### PR DESCRIPTION
**Pull request by danoscarmike**
Samples from https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/video/cloud-client/labels

### CODE REVIEW

**Comment by busunkim96** [comment]
Samples look good! Could the `noxfile.py` also be added via `synth.py`?

**Comment by danoscarmike** [comment]
Ah, sorry about the churn here. I think if we can land earlier PR first we'll be good. @busunkim96 PTAL #48

**Comment by danoscarmike** [comment]
Moving samples from another repository (python-docs-samples)

**Review by busunkim96 — APPROVED** [review]

**Comment by danoscarmike** [comment]
@sirtorry @telpirion could I get a quick review on this one? Thank you!

**Review by sirtorry — APPROVED** [review]

**Pull request merged**
